[tool.poetry]
name = "Hackathon"
version = "0.1.0"
description = ""
authors = ["VISN"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt5 = "^5.15.10"
pyqt6 = "^6.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"